Implement dark mode for reg-lite widget
fntechgit/summit-registration-lite pull request #67
Opened 2023-08-10 15:57 UTC by tomrndom

ref: https://tipit.avaza.com/project/view#!tab=task-pane&groupby=MyTaskProject&view=vertical&task=3351853&stafilter=NotComplete&fileview=grid

Signed-off-by: Tomás Castillo <tcastilloboireau@gmail.com>

2023-08-10 17:21 UTC, smarcet commented on src/components/login-passwordless/index.module.scss
> +      background-color: #fff;
remove this

2023-08-10 17:23 UTC, smarcet commented on src/components/stripe-form/index.js
> +            color: marketingData.color_input_text_color,
what about is not defined ?

2023-08-10 17:23 UTC, smarcet commented on src/components/stripe-form/index.js
> +            backgroundColor: marketingData.color_input_background_color,
same here

2023-08-10 21:08 UTC, smarcet commented on src/components/stripe-form/index.js
> +            backgroundColor: marketingData.color_input_background_color || '#ffffff',
same here

2023-08-10 21:09 UTC, smarcet requested changes
@tomrndom please review comments

2023-08-13 02:55 UTC, S-code652 approved these changes

2023-08-25 15:01 UTC, smarcet approved these changes
LGTM

2023-08-25 15:01 UTC, merged